### ISSUE TITLE
[BUG] UI is also showing when flying with Tulip Snakes

### ISSUE THREAD

**Issue by IAmSympathy** [Rumi727/Jetpack-HMD#2]
When Tulip Snakes make you fly, the Jetpack UI will be shown
![image](https://github.com/Rumi727/Jetpack-HMD/assets/110695959/7f1b63ee-17c7-4317-bbb4-ced8d8c7a7ab)

**Comment by Rumi727** [comment]
I discovered it as soon as v50 was updated, but I'd like to leave it alone because it's fun
Because it is also called a biological “jetpack” lol.
(In fact, in the code, it is the same as a tulip snakes and a jetpack)

Well... Anyway, I'll add a function to ignore the tulip snakes.

**Comment by Rumi727** [comment]
I just added a setting to display the UI when flying with the Tulip Snakes!
